import type { Product } from '../../../modules/shop/types';

export const productsChunks: Record<number, Product[]> = {
  0: require('../../../data/products/chunk-0.json') as Product[],
  1: require('../../../data/products/chunk-1.json') as Product[],
  2: require('../../../data/products/chunk-2.json') as Product[],
  3: require('../../../data/products/chunk-3.json') as Product[],
  4: require('../../../data/products/chunk-4.json') as Product[],
  5: require('../../../data/products/chunk-5.json') as Product[],
  6: require('../../../data/products/chunk-6.json') as Product[],
  7: require('../../../data/products/chunk-7.json') as Product[],
  8: require('../../../data/products/chunk-8.json') as Product[],
  9: require('../../../data/products/chunk-9.json') as Product[],
  10: require('../../../data/products/chunk-10.json') as Product[],
  11: require('../../../data/products/chunk-11.json') as Product[],
  12: require('../../../data/products/chunk-12.json') as Product[],
  13: require('../../../data/products/chunk-13.json') as Product[],
  14: require('../../../data/products/chunk-14.json') as Product[],
  15: require('../../../data/products/chunk-15.json') as Product[],
  16: require('../../../data/products/chunk-16.json') as Product[],
  17: require('../../../data/products/chunk-17.json') as Product[],
  18: require('../../../data/products/chunk-18.json') as Product[],
  19: require('../../../data/products/chunk-19.json') as Product[],
  20: require('../../../data/products/chunk-20.json') as Product[],
  21: require('../../../data/products/chunk-21.json') as Product[],
  22: require('../../../data/products/chunk-22.json') as Product[],
  23: require('../../../data/products/chunk-23.json') as Product[],
  24: require('../../../data/products/chunk-24.json') as Product[],
  25: require('../../../data/products/chunk-25.json') as Product[],
  26: require('../../../data/products/chunk-26.json') as Product[],
  27: require('../../../data/products/chunk-27.json') as Product[],
  28: require('../../../data/products/chunk-28.json') as Product[],
  29: require('../../../data/products/chunk-29.json') as Product[],
  30: require('../../../data/products/chunk-30.json') as Product[],
  31: require('../../../data/products/chunk-31.json') as Product[],
  32: require('../../../data/products/chunk-32.json') as Product[],
  33: require('../../../data/products/chunk-33.json') as Product[],
  34: require('../../../data/products/chunk-34.json') as Product[],
  35: require('../../../data/products/chunk-35.json') as Product[],
  36: require('../../../data/products/chunk-36.json') as Product[],
  37: require('../../../data/products/chunk-37.json') as Product[],
  38: require('../../../data/products/chunk-38.json') as Product[],
  39: require('../../../data/products/chunk-39.json') as Product[],
};

export const productsManifest = require('../../../data/products/manifest.json') as { total: number; chunkSize: number; chunks: number };
